### PR TITLE
fix(lvgl_port): Fixed deinitialization of the task which was created with caps + lv_deinit()

### LINKED ISSUE #635: LVGL 9 doesn't use LV_MEM_CUSTOM or LV_ENABLE_GC (BSP-714)
### Board

ESP32S3-WROOM1-N16R8 Custom Board

### Hardware Description

LCD RGB565 480x854

### IDE Name

VSCode

### Operating System

Windows 11

### Description

in /lvgl9/esp_lvgl_port.c
function lvgl_port_task_deinit

lv_deinit is only called for the following
#if LV_ENABLE_GC || !LV_MEM_CUSTOM

Neither of which is in LVGL9

I think it should be
#if LV_USE_STDLIB_MALLOC == LV_STDLIB_BUILTIN

### Sketch

```cpp
esp_err_t test_dev_lcd_lvgl_deinit(void)
{
    esp_err_t ret = ESP_OK;

    // Remove display from LVGL
    if (disp != NULL) {
        ret = lvgl_port_remove_disp(disp);
        ESP_RETURN_ON_ERROR(ret, TAG, "Failed to remove display from LVGL");
        disp = NULL;
    }

    ESP_ERROR_CHECK(esp_lcd_panel_del(panel_handle));
    panel_handle = NULL;

    // Deinitialize LVGL port
    ret = lvgl_port_deinit();
    ESP_RETURN_ON_ERROR(ret, TAG, "Failed to deinitialize LVGL port");

    return ESP_OK;
}

void deinit()
{
    ESP_ERROR_CHECK(lvgl_port_stop());
    vTaskDelay(pdMS_TO_TICKS(100));
    ESP_ERROR_CHECK(test_dev_lcd_lvgl_deinit());
}
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, README.md and ESP32 Forum

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### LINKED ISSUE #680: esp_lvgl_port: Memory leakage in call lvgl_port_deinit (BSP-743)
### Board

esp32s3_korvo_v2

### Hardware Description

No special

### IDE Name

esp-idf

### Operating System

ubuntu

### Description

New API use _Caps to create task but not use _Caps to delete task
Code at https://github.com/espressif/esp-bsp/blob/master/components/esp_lvgl_port/src/lvgl9/esp_lvgl_port.c#L255

need call API `vTaskDeleteWithCaps( NULL );` instead.

Leakage log as:
```
====== Heap Trace: 8 records (500 capacity) ======
   352 bytes (@ 0x3fceeba0, Internal) allocated CPU 0 ccount 0x0e7e5a90 caller 0x4037a080:0x40386ec8:0x420a4556:0x420105e1:0x4200afb1:0x4200b46e
--- 0x4037a080: heap_caps_malloc at /home/tempo/esp/idf_v55/esp-idf/components/heap/heap_caps.c:83
--- 0x40386ec8: pvPortMalloc at /home/tempo/esp/idf_v55/esp-idf/components/freertos/heap_idf.c:58
--- 0x420a4556: xTaskCreatePinnedToCoreWithCaps at /home/tempo/esp/idf_v55/esp-idf/components/freertos/esp_additions/idf_additions.c:50
--- 0x420105e1: lvgl_port_init at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../managed_components/espressif__esp_lvgl_port/src/lvgl9/esp_lvgl_port.c:86
--- 0x4200afb1: init_lvgl_display_from_board at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:56
--- 0x4200b46e: create_video_render at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:221
  7168 bytes (@ 0x3fcbfce0, Internal) allocated CPU 0 ccount 0x0e7e6358 caller 0x4037a080:0x420a4564:0x420105e1:0x4200afb1:0x4200b46e:0x4200acc4
--- 0x4037a080: heap_caps_malloc at /home/tempo/esp/idf_v55/esp-idf/components/heap/heap_caps.c:83
--- 0x420a4564: xTaskCreatePinnedToCoreWithCaps at /home/tempo/esp/idf_v55/esp-idf/components/freertos/esp_additions/idf_additions.c:52
--- 0x420105e1: lvgl_port_init at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../managed_components/espressif__esp_lvgl_port/src/lvgl9/esp_lvgl_port.c:86
--- 0x4200afb1: init_lvgl_display_from_board at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:56
--- 0x4200b46e: create_video_render at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:221
--- 0x4200acc4: video_render_play_one_video at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render.c:418

0x4037a080:0x40386ec8:0x420a4556:0x420105e1:0x4200afb1:0x4200b46e
--- 0x4037a080: heap_caps_malloc at /home/tempo/esp/idf_v55/esp-idf/components/heap/heap_caps.c:83
--- 0x40386ec8: pvPortMalloc at /home/tempo/esp/idf_v55/esp-idf/components/freertos/heap_idf.c:58
--- 0x420a4556: xTaskCreatePinnedToCoreWithCaps at /home/tempo/esp/idf_v55/esp-idf/components/freertos/esp_additions/idf_additions.c:50
--- 0x420105e1: lvgl_port_init at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../managed_components/espressif__esp_lvgl_port/src/lvgl9/esp_lvgl_port.c:86
--- 0x4200afb1: init_lvgl_display_from_board at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:56
--- 0x4200b46e: create_video_render at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:221
  7168 bytes (@ 0x3fcc1a48, Internal) allocated CPU 0 ccount 0xa0b8db64 caller 0x4037a080:0x420a4564:0x420105e1:0x4200afb1:0x4200b46e:0x4200ae21
--- 0x4037a080: heap_caps_malloc at /home/tempo/esp/idf_v55/esp-idf/components/heap/heap_caps.c:83
--- 0x420a4564: xTaskCreatePinnedToCoreWithCaps at /home/tempo/esp/idf_v55/esp-idf/components/freertos/esp_additions/idf_additions.c:52
--- 0x420105e1: lvgl_port_init at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../managed_components/espressif__esp_lvgl_port/src/lvgl9/esp_lvgl_port.c:86
--- 0x4200afb1: init_lvgl_display_from_board at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:56
--- 0x4200b46e: create_video_render at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:221
--- 0x4200ae21: video_render_play_dual_video_with_progress at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render.c:503
   352 bytes (@ 0x3fcc364c, Internal) allocated CPU 0 ccount 0x388acaf0 caller 0x4037a080:0x40386ec8:0x420a4556:0x420105e1:0x4200afb1:0x4200b46e
--- 0x4037a080: heap_caps_malloc at /home/tempo/esp/idf_v55/esp-idf/components/heap/heap_caps.c:83
--- 0x40386ec8: pvPortMalloc at /home/tempo/esp/idf_v55/esp-idf/components/freertos/heap_idf.c:58
--- 0x420a4556: xTaskCreatePinnedToCoreWithCaps at /home/tempo/esp/idf_v55/esp-idf/components/freertos/esp_additions/idf_additions.c:50
--- 0x420105e1: lvgl_port_init at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../managed_components/espressif__esp_lvgl_port/src/lvgl9/esp_lvgl_port.c:86
--- 0x4200afb1: init_lvgl_display_from_board at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:56
--- 0x4200b46e: create_video_render at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:221
  7168 bytes (@ 0x3fcc37b0, Internal) allocated CPU 0 ccount 0x388ad598 caller 0x4037a080:0x420a4564:0x420105e1:0x4200afb1:0x4200b46e:0x4200ad31
--- 0x4037a080: heap_caps_malloc at /home/tempo/esp/idf_v55/esp-idf/components/heap/heap_caps.c:83
--- 0x420a4564: xTaskCreatePinnedToCoreWithCaps at /home/tempo/esp/idf_v55/esp-idf/components/freertos/esp_additions/idf_additions.c:52
--- 0x420105e1: lvgl_port_init at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../managed_components/espressif__esp_lvgl_port/src/lvgl9/esp_lvgl_port.c:86
--- 0x4200afb1: init_lvgl_display_from_board at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:56
--- 0x4200b46e: create_video_render at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render_sys.c:221
--- 0x4200ad31: video_render_play_dual_video at /home/tempo/ttt/latest_gmf/esp-gmf/packages/esp_video_render/examples/video_render/build/../main/video_render.c:459
====== Heap Trace Summary ======
Mode: Heap Trace Leaks
23080 bytes 'leaked' in trace (8 allocations)
records: 8 (500 capacity, 183 high water mark)
total allocations: 17882
total frees: 21932
================================
```

### Sketch

```cpp
NA
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, README.md and ESP32 Forum

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by espzav**
# ESP-BSP Pull Request checklist

~[ ] Version of modified component bumped~
- [ ] CI passing

# Change description
- Fixed deinitialization of the task which was created with caps - Closes #680 
- Call lv_deinit() - Closes #635

### CODE REVIEW

File: components/esp_lvgl_port/test_apps/lvgl_port/main/test.c [hunk 1]
```diff
@@ -209,7 +209,7 @@ static esp_err_t app_touch_deinit(void)
     return ESP_OK;
 }
 
-static esp_err_t app_lvgl_init(void)
+static esp_err_t app_lvgl_init(int task_affinity)
```
Comment (PetrESP) [inline components/esp_lvgl_port/test_apps/lvgl_port/main/test.c:212]: The task affinity doesn't seem to be used

File: components/esp_lvgl_port/test_apps/lvgl_port/main/test.c [hunk 2]
```diff
@@ -306,7 +306,7 @@ static void app_main_display(void)
 }
 
 // Some resources are lazy allocated in the LCD driver, the threadhold is left for that case
-#define TEST_MEMORY_LEAK_THRESHOLD (50)
+#define TEST_MEMORY_LEAK_THRESHOLD (200)
```
Comment (PetrESP) [inline components/esp_lvgl_port/test_apps/lvgl_port/main/test.c:310]: For my information: why do we need to increase it? Is there something which is getting worse?

File: components/esp_lvgl_port/test_apps/lvgl_port/main/test.c (hunk 1 above)
Comment (espzav) [reply components/esp_lvgl_port/test_apps/lvgl_port/main/test.c:212]: Oh, thanks. I fixed and tested again.

File: components/esp_lvgl_port/test_apps/lvgl_port/main/test.c (hunk 2 above)
Comment (espzav) [reply components/esp_lvgl_port/test_apps/lvgl_port/main/test.c:310]: It is not getting worse, it was failing before... Now, there is still 148 bytes.

Comment (PetrESP) [reply components/esp_lvgl_port/test_apps/lvgl_port/main/test.c:310]: Got it. Thank you
